server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: text_public
          uri: http://localhost:8080/
          predicates:
            - Path=/kakao/**

        - id: text_user
          uri: http://localhost:8080/
          predicates:
            - Path=/summaries/**
          filters:
            - JwtAuthenticationFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:5173" 
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST, DELETE

jwt:
  secret: 5asf46g8asg56hesh8j65j4g23agw874rq564asg56h48ry47sd65g4ag8q